export const FETCH_DRIVERS_REQUEST = 'FETCH_DRIVERS_REQUEST';
export const FETCH_DRIVERS_SUCCESS = 'FETCH_DRIVERS_SUCCESS';
export const FETCH_DRIVERS_ERROR = 'FETCH_DRIVERS_ERROR';

export const FETCH_DRIVER_STATUSES_REQUEST = 'FETCH_DRIVER_STATUSES_REQUEST';
export const FETCH_DRIVER_STATUSES_SUCCESS = 'FETCH_DRIVER_STATUSES_SUCCESS';
export const FETCH_DRIVER_STATUSES_ERROR = 'FETCH_DRIVER_STATUSES_ERROR';

export const ADD_DRIVER_REQUEST = 'ADD_DRIVER_REQUEST';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';
export const ADD_DRIVER_ERROR = 'ADD_DRIVER_ERROR';

export const UPDATE_DRIVER_INFO_REQUEST = 'UPDATE_DRIVER_INFO_REQUEST';
export const UPDATE_DRIVER_INFO_SUCCESS = 'UPDATE_DRIVER_INFO_SUCCESS';
export const UPDATE_DRIVER_INFO_ERROR = 'UPDATE_DRIVER_INFO_ERROR';

export const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
export const DELETE_DRIVER_ERROR = 'DELETE_DRIVER_ERROR';

export const SORT_ITEMS_DRIVER = 'CHOISE_PARAMETR_SORT';
