const FETCH_DRIVERS_REQUEST = 'FETCH_DRIVERS_REQUEST';
const FETCH_DRIVERS_SUCCESS = 'FETCH_DRIVERS_SUCCESS';
const FETCH_DRIVERS_ERROR = 'FETCH_DRIVERS_ERROR';

const FETCH_DRIVER_STATUSES_REQUEST = 'FETCH_DRIVER_STATUSES_REQUEST';
const FETCH_DRIVER_STATUSES_SUCCESS = 'FETCH_DRIVER_STATUSES_SUCCESS';
const FETCH_DRIVER_STATUSES_ERROR = 'FETCH_DRIVER_STATUSES_ERROR';

const ADD_DRIVER_REQUEST = 'ADD_DRIVER_REQUEST';
const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';
const ADD_DRIVER_ERROR = 'ADD_DRIVER_ERROR';

const UPDATE_DRIVER_INFO_REQUEST = 'UPDATE_DRIVER_INFO_REQUEST';
const UPDATE_DRIVER_INFO_SUCCESS = 'UPDATE_DRIVER_INFO_SUCCESS';
const UPDATE_DRIVER_INFO_ERROR = 'UPDATE_DRIVER_INFO_ERROR';

const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST';
const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
const DELETE_DRIVER_ERROR = 'DELETE_DRIVER_ERROR';

const SORT_ITEMS_DRIVER = 'SORT_ITEMS_DRIVER';

export {
    FETCH_DRIVERS_REQUEST,
    FETCH_DRIVERS_SUCCESS,
    FETCH_DRIVERS_ERROR,
    FETCH_DRIVER_STATUSES_REQUEST,
    FETCH_DRIVER_STATUSES_SUCCESS,
    FETCH_DRIVER_STATUSES_ERROR,
    ADD_DRIVER_REQUEST,
    ADD_DRIVER_SUCCESS,
    ADD_DRIVER_ERROR,
    UPDATE_DRIVER_INFO_REQUEST,
    UPDATE_DRIVER_INFO_SUCCESS,
    UPDATE_DRIVER_INFO_ERROR,
    DELETE_DRIVER_REQUEST,
    DELETE_DRIVER_SUCCESS,
    DELETE_DRIVER_ERROR,
    SORT_ITEMS_DRIVER,
};
