export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';

export const FETCH_CAR_STATUSES_REQUEST = 'FETCH_CAR_STATUSES_REQUEST';
export const FETCH_CAR_STATUSES_SUCCESS = 'FETCH_CAR_STATUSES_SUCCESS';
export const FETCH_CAR_STATUSES_ERROR = 'FETCH_CAR_STATUSES_ERROR';

export const ADD_CAR_REQUEST = 'ADD_CAR_REQUEST';
export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const ADD_CAR_ERROR = 'ADD_CAR_ERROR';

export const UPDATE_CAR_INFO_REQUEST = 'UPDATE_CAR_INFO_REQUEST';
export const UPDATE_CAR_INFO_SUCCESS = 'UPDATE_CAR_INFO_SUCCESS';
export const UPDATE_CAR_INFO_ERROR = 'UPDATE_CAR_INFO_ERROR';

export const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const DELETE_CAR_ERROR = 'DELETE_CAR_ERROR';

export const CHOISE_PARAMETR_SORT = 'CHOISE_PARAMETR_SORT';
