const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';

const FETCH_CAR_STATUSES_REQUEST = 'FETCH_CAR_STATUSES_REQUEST';
const FETCH_CAR_STATUSES_SUCCESS = 'FETCH_CAR_STATUSES_SUCCESS';
const FETCH_CAR_STATUSES_ERROR = 'FETCH_CAR_STATUSES_ERROR';

const ADD_CAR_REQUEST = 'ADD_CAR_REQUEST';
const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
const ADD_CAR_ERROR = 'ADD_CAR_ERROR';

const UPDATE_CAR_INFO_REQUEST = 'UPDATE_CAR_INFO_REQUEST';
const UPDATE_CAR_INFO_SUCCESS = 'UPDATE_CAR_INFO_SUCCESS';
const UPDATE_CAR_INFO_ERROR = 'UPDATE_CAR_INFO_ERROR';

const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
const DELETE_CAR_ERROR = 'DELETE_CAR_ERROR';

const SORT_ITEMS_CAR = 'SORT_ITEMS_CAR';

export {
    FETCH_CARS_REQUEST,
    FETCH_CARS_SUCCESS,
    FETCH_CARS_ERROR,
    FETCH_CAR_STATUSES_REQUEST,
    FETCH_CAR_STATUSES_SUCCESS,
    FETCH_CAR_STATUSES_ERROR,
    ADD_CAR_REQUEST,
    ADD_CAR_SUCCESS,
    ADD_CAR_ERROR,
    UPDATE_CAR_INFO_REQUEST,
    UPDATE_CAR_INFO_SUCCESS,
    UPDATE_CAR_INFO_ERROR,
    DELETE_CAR_REQUEST,
    DELETE_CAR_SUCCESS,
    DELETE_CAR_ERROR,
    SORT_ITEMS_CAR,
};
